#import <React/RCTViewManager.h>
#import "MobileRecorder-Swift.h"

// Exposes BroadcastPickerView (Swift) to JS as requireNativeComponent('BroadcastPickerView').
// "MobileRecorder-Swift.h" is auto-generated by Xcode for any target containing
// Swift files — no manual bridging header needed for this ObjC-imports-Swift direction.
@interface BroadcastPickerViewManager : RCTViewManager
@end

@implementation BroadcastPickerViewManager

RCT_EXPORT_MODULE(BroadcastPickerView)

- (UIView *)view
{
  return [[BroadcastPickerView alloc] init];
}

@end
